name: jlite-build
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyter_server
  - jupyterlite-core
  - jupyterlite-xeus
  - jupyterlite-pyodide-kernel
  - jupyterlite-terminal
  - nodejs=20
